[project]
name = "headway-dev"
version = "0.1.0"
description = "A development environment for developing at Headway with AI agents."
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["pydantic-settings>=2.12.0", "typer>=0.21.1"]

[project.scripts]
hwdev = "headway_dev.app:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["basedpyright>=1.37.4", "ruff>=0.15.0"]
